apiVersion: v1
kind: Pod
metadata:
  name: tridentctl-protect-scratch
  namespace: trident-protect
spec:
  restartPolicy: Never
  containers:
    - name: tridentctl-protect-scratch
      image: quay.io/yvosonthehub/tridentctl-protect:scratch-25.10.0
      command: ["/tridentctl-protect"]
      args: ["get","appvaultcontent","ontap-vault","--show-resources","all","-n","trident-protect"]
  serviceAccountName: trident-protect-controller-manager